# Generated by Django 5.0.7 on 2024-08-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accountsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
