# Generated by Django 5.0.7 on 2024-08-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accountsapp', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
