# Generated by Django 5.0.7 on 2024-07-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oraganizerdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eventid', models.IntegerField()),
                ('Eventname', models.CharField(max_length=40)),
                ('Eventlocation', models.CharField(max_length=200)),
                ('Eventimage', models.ImageField(upload_to='static')),
                ('EventTime', models.TimeField()),
                ('Eventdate', models.DateField()),
                ('Eventcost', models.IntegerField()),
                ('Organizerinfo', models.CharField(max_length=300)),
            ],
        ),
    ]
