# Generated by Django 5.0.7 on 2024-07-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventorganizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oraganizerdata',
            old_name='Eventdate',
            new_name='event_Date',
        ),
        migrations.RenameField(
            model_name='oraganizerdata',
            old_name='Eventcost',
            new_name='event_Id',
        ),
        migrations.RenameField(
            model_name='oraganizerdata',
            old_name='Eventimage',
            new_name='event_Image',
        ),
        migrations.RenameField(
            model_name='oraganizerdata',
            old_name='Eventlocation',
            new_name='event_Location',
        ),
        migrations.RenameField(
            model_name='oraganizerdata',
            old_name='Eventname',
            new_name='event_Name',
        ),
        migrations.RenameField(
            model_name='oraganizerdata',
            old_name='Eventid',
            new_name='event_Price',
        ),
        migrations.RenameField(
            model_name='oraganizerdata',
            old_name='EventTime',
            new_name='event_Time',
        ),
        migrations.RenameField(
            model_name='oraganizerdata',
            old_name='Organizerinfo',
            new_name='event_orginfo',
        ),
    ]
