# Generated by Django 5.0.7 on 2024-07-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventorganizer', '0002_rename_eventdate_oraganizerdata_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oraganizerdata',
            name='event_Image',
            field=models.ImageField(upload_to='showevents/'),
        ),
    ]
