# Generated by Django 5.0.7 on 2024-07-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventorganizer', '0003_alter_oraganizerdata_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oraganizerdata',
            name='event_Image',
            field=models.ImageField(upload_to='static'),
        ),
    ]
