# Generated by Django 5.0.7 on 2024-08-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventorganizer', '0005_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='oraganizerdata',
            name='organizerid',
            field=models.CharField(default='Rollno', max_length=8),
            preserve_default=False,
        ),
    ]
