# Generated by Django 5.0.7 on 2024-08-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventorganizer', '0006_oraganizerdata_organizerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registeredto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('username', models.CharField(max_length=40)),
                ('eventid', models.IntegerField()),
                ('eventname', models.CharField(max_length=40)),
                ('organizerid', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Registrations',
        ),
    ]
