# Generated by Django 5.0.7 on 2024-08-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventorganizer', '0008_registrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='student',
        ),
    ]
