# Generated by Django 5.0.7 on 2024-08-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventorganizer', '0009_remove_registrations_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registrations',
        ),
    ]
